apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  nodeSelector:
    kubernetes.io/hostname: gke-cluster-1-micro-a0f27b19-node-s77w
  restartPolicy: Always
