apiVersion: v1
kind: Pod
metadata:
  name: newsaggregator
spec:
  containers:
    - name: newsaggregator
      image: gcr.io/chat-app-proto01/news_aggregator_n
      env:
        - name: COREOS_PRIVATE_IPV4
          value:
      ports:
        - containerPort: 3000
          hostPort: 3000
