apiVersion: v1
kind: ReplicationController
metadata:
  name: newsaggregator
  labels:
    name: newsaggregator
spec:
  replicas: 2
  selector:
    name: newsaggregator
    version: v0
  template:
    metadata:
      labels:
        name: newsaggregator
        version: v0
    spec:
      containers:
      - name: newsaggregator
        image: gcr.io/chat-app-proto01/news_aggregator_n:latest
        env:
          - name: COREOS_PRIVATE_IPV4
            value: 130.211.255.234
        ports:
        - containerPort: 3000
          hostPort: 3000
