apiVersion: v1
kind: Service
metadata:
  name: news-aggregator-web
  labels:
    name: news-aggregator-web
spec:
  ports:
    # the port that this service should serve on
  - port: 3000
    targetPort: 3000
  selector:
    name: newsaggregator
